# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://SpellOnYou.github.io/nbdev_dionne/"

git_url = "https://github.com/SpellOnYou/nbdev_dionne/tree/master/"

def custom_doc_links(name): return None
